// Generated by entitler generate. Do not edit.
// Read from development, All customers, release 2.

import { defineFeature } from "@entitlerhq/entitler";

/** The features of the Entitler catalogue, by constant name. */
export const features = {
  /**
   * AI credits
   *
   * Spent on AI actions each month.
   *
   * Counted in credits.
   */
  aiCredits: defineFeature("ai_credits", "metered"),
  /**
   * Collaboration
   *
   * Includes team_seats, shared_folders.
   */
  collaboration: defineFeature("collaboration", "group", [
    "team_seats",
    "shared_folders",
  ]),
  /**
   * Export to PDF
   *
   * Download any document as a PDF.
   * Keeps *\/ comments safe.
   */
  exportPdf: defineFeature("export_pdf", "boolean"),
  /**
   * Priority support
   *
   * @deprecated Archived in Entitler.
   */
  prioritySupport: defineFeature("priority_support", "boolean"),
  /** shared_folders */
  sharedFolders: defineFeature("shared_folders", "boolean"),
  /**
   * Support extras
   *
   * Includes priority_support, team_essentials.
   */
  supportExtras: defineFeature("support_extras", "group", [
    "priority_support",
    "team_seats",
    "shared_folders",
  ]),
  /**
   * Team essentials
   *
   * Includes collaboration, support_extras, team_seats, unknown_key.
   */
  teamEssentials: defineFeature("team_essentials", "group", [
    "team_seats",
    "shared_folders",
    "priority_support",
  ]),
  /**
   * Team seats
   *
   * Counted in seats.
   */
  teamSeats: defineFeature("team_seats", "config"),
} as const;
