// Generated by entitler generate. Do not edit.
// Read from development, All customers, release 2.

/** The features of the Entitler catalogue, by constant name. */
export const features = {} as const;
