// Generated by entitler generate. Do not edit.
// Read from development, All customers, release 2.

import { defineFeature } from "@entitlerhq/entitler";

/** The features of the Entitler catalogue, by constant name. */
export const features = {
  /** 2fa */
  _2fa: defineFeature("2fa", "boolean"),
  /** __ */
  _: defineFeature("__", "boolean"),
  /** a.b */
  aB: defineFeature("a.b", "boolean"),
  /** class */
  class_: defineFeature("class", "boolean"),
  /** delete */
  delete_: defineFeature("delete", "boolean"),
  /** export-pdf */
  exportPdf: defineFeature("export-pdf", "boolean"),
  /** exportPdf */
  exportPdf2: defineFeature("exportPdf", "boolean"),
  /** export_pdf */
  exportPdf3: defineFeature("export_pdf", "boolean"),
  /** new_ */
  new_: defineFeature("new_", "boolean"),
} as const;
