// Generated by entitler generate. Do not edit.
// Read from development, All customers, release 2.

import { defineFeature } from "@entitlerhq/entitler";

/** The features of the Entitler catalogue, by constant name. */
export const features = {
  /** audit_log */
  auditLog: defineFeature("audit_log", "boolean"),
  /** export_pdf */
  pdfExport: defineFeature("export_pdf", "boolean"),
  /** pdf_export */
  pdfExport2: defineFeature("pdf_export", "boolean"),
  /** sso */
  sso: defineFeature("sso", "boolean"),
} as const;
