// Generated by entitler generate. Do not edit.
// Read from development, All customers, release 2.

import { defineFeature } from "@entitlerhq/entitler";

/** The features of the Entitler catalogue, by constant name. */
export const features = {
  /**
   * AI credits
   *
   * Spent on AI actions each month.
   *
   * Counted in credits.
   */
  aiCredits: defineFeature("ai_credits", "metered"),
  /**
   * Collaboration
   *
   * Working with other people.
   *
   * Includes team_seats, shared_folders.
   */
  collaboration: defineFeature("collaboration", "group", ["team_seats", "shared_folders"]),
  /**
   * Export to PDF
   *
   * Download any document as a PDF.
   */
  exportPdf: defineFeature("export_pdf", "boolean"),
  /**
   * Team seats
   *
   * Counted in seats.
   */
  teamSeats: defineFeature("team_seats", "config"),
} as const;
