import type { FeatureListing } from "./types.js";

/** The catalogue a generated file is rendered from: what `features()` answers. */
export interface FeatureSource {
  /** The environment read. */
  readonly environment: { readonly name: string };
  /** The track read. */
  readonly track: { readonly name: string };
  /** The release read, or `null`. */
  readonly release: number | null;
  /** The change read, or `null`. */
  readonly change: string | null;
  /** The features. */
  readonly features: readonly Pick<
    FeatureListing,
    "key" | "name" | "type" | "description" | "unit" | "archived" | "includes"
  >[];
}

/** Options for {@link renderFeatures}. */
export interface RenderOptions {
  /** The current contents of the generated file, so each feature keeps the constant name it had. */
  readonly existing?: string;
}

const HEADER = "// Generated by entitler generate. Do not edit.";
const READ_FROM = /^\/\/ Read from .*$/m;
const LINE_WIDTH = 80;
const RESERVED = new Set(
  (
    "abstract any arguments as async await boolean break case catch class const constructor continue debugger declare " +
    "default delete do else enum eval export extends false finally for from function get if implements import in " +
    "infer instanceof interface is keyof let module namespace never new null number object of package private " +
    "protected public readonly require return satisfies set static string super switch symbol this throw true try " +
    "type typeof undefined unique unknown var void while with yield"
  ).split(" "),
);
const KEPT = /^ {2}([A-Za-z_$][\w$]*): defineFeature\(\s*("(?:[^"\\]|\\.)*")/gm;

function camel(key: string): string {
  const words = key.split(/[^A-Za-z0-9]+/).filter(Boolean);
  return words
    .map((word, index) =>
      index === 0 ? word.charAt(0).toLowerCase() + word.slice(1) : word.charAt(0).toUpperCase() + word.slice(1),
    )
    .join("");
}

function baseName(key: string): string {
  const name = camel(key);
  if (name === "" || /^[0-9]/.test(name)) return `_${name}`;
  return RESERVED.has(name) ? `${name}_` : name;
}

/** Decides each key's constant name: kept names first, then new ones in key order. @internal */
export function constantNames(keys: readonly string[], existing = ""): Map<string, string> {
  const names = new Map<string, string>();
  const taken = new Set<string>();
  const listed = new Set(keys);
  for (const match of existing.matchAll(KEPT)) {
    const [, name, quoted] = match as unknown as [string, string, string];
    const key = JSON.parse(quoted) as string;
    if (listed.has(key) && !names.has(key) && !taken.has(name)) {
      names.set(key, name);
      taken.add(name);
    }
  }
  for (const key of [...keys].sort()) {
    if (names.has(key)) continue;
    const base = baseName(key);
    let name = base;
    for (let n = 2; taken.has(name); n += 1) name = `${base}${n}`;
    names.set(key, name);
    taken.add(name);
  }
  return names;
}

function leaves(key: string, byKey: Map<string, FeatureSource["features"][number]>): string[] {
  const out: string[] = [];
  const seen = new Set<string>([key]);
  const visit = (members: readonly string[]) => {
    for (const member of members) {
      if (seen.has(member)) continue;
      seen.add(member);
      const feature = byKey.get(member);
      if (!feature) continue;
      if (feature.type === "group") visit(feature.includes);
      else out.push(member);
    }
  };
  visit(byKey.get(key)?.includes ?? []);
  return out;
}

function docLines(feature: FeatureSource["features"][number]): string[] {
  const lines = [feature.name.trim() || feature.key];
  const description = feature.description.trim();
  if (description) lines.push("", ...description.split(/\r?\n/).map((line) => line.trimEnd()));
  if (feature.unit.trim()) lines.push("", `Counted in ${feature.unit.trim()}.`);
  if (feature.type === "group" && feature.includes.length) lines.push("", `Includes ${feature.includes.join(", ")}.`);
  if (feature.archived) lines.push("", "@deprecated Archived in Entitler.");
  return lines.map((line) => line.replace(/\*\//g, "*\\/"));
}

function comment(lines: string[]): string[] {
  if (lines.length === 1) return [`  /** ${lines[0]} */`];
  return ["  /**", ...lines.map((line) => (line ? `   * ${line}` : "   *")), "   */"];
}

function call(indent: string, args: string[], quoted: string[]): string[] {
  const inner = `${indent}  `;
  const array = `${inner}[${quoted.join(", ")}],`;
  const members = !quoted.length
    ? []
    : array.length <= LINE_WIDTH
      ? [array]
      : [`${inner}[`, ...quoted.map((member) => `${inner}  ${member},`), `${inner}],`];
  return [...args.map((arg) => `${inner}${arg},`), ...members, `${indent}),`];
}

function constant(name: string, feature: FeatureSource["features"][number], members: string[]): string[] {
  const args = [JSON.stringify(feature.key), JSON.stringify(feature.type)];
  const quoted = members.map((member) => JSON.stringify(member));
  const all = [...args, ...(quoted.length ? [`[${quoted.join(", ")}]`] : [])];
  const inline = `  ${name}: defineFeature(${all.join(", ")}),`;
  if (inline.length <= LINE_WIDTH) return [inline];
  const hugged = `  ${name}: defineFeature(${args.join(", ")}, [`;
  if (quoted.length && hugged.length <= LINE_WIDTH)
    return [hugged, ...quoted.map((member) => `    ${member},`), "  ]),"];
  const opening = `  ${name}: defineFeature(`;
  if (opening.length <= LINE_WIDTH) return [opening, ...call("  ", args, quoted)];
  const broken = `    defineFeature(${all.join(", ")}),`;
  if (broken.length <= LINE_WIDTH) return [`  ${name}:`, broken];
  return [`  ${name}:`, "    defineFeature(", ...call("    ", args, quoted)];
}

function readFrom(source: FeatureSource): string {
  const catalogue =
    source.change !== null && source.release === null
      ? `change ${source.change}`
      : `release ${source.release ?? "none"}`;
  return `// Read from ${source.environment.name}, ${source.track.name}, ${catalogue}.`;
}

/**
 * Renders the source of a generated features file: one typed constant per feature, sorted by
 * key, each with its doc comment. Pass the current file as `existing` so every feature keeps
 * its constant's name.
 *
 * @example
 * ```ts
 * import { EntitlerServer } from "@entitlerhq/entitler";
 * import { renderFeatures } from "@entitlerhq/entitler/generate";
 *
 * const source = renderFeatures(await new EntitlerServer({ key }).features());
 * ```
 */
export function renderFeatures(source: FeatureSource, options: RenderOptions = {}): string {
  const features = [...source.features].sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
  const byKey = new Map(features.map((feature) => [feature.key, feature]));
  const names = constantNames(
    features.map((feature) => feature.key),
    options.existing,
  );
  const lines = [HEADER, readFrom(source), ""];
  if (features.length) {
    lines.push('import { defineFeature } from "@entitlerhq/entitler";', "");
    lines.push("/** The features of the Entitler catalogue, by constant name. */", "export const features = {");
    for (const feature of features) {
      const members = feature.type === "group" ? leaves(feature.key, byKey) : [];
      lines.push(...comment(docLines(feature)), ...constant(names.get(feature.key) as string, feature, members));
    }
    lines.push("} as const;");
  } else {
    lines.push(
      "/** The features of the Entitler catalogue, by constant name. */",
      "export const features = {} as const;",
    );
  }
  return `${lines.join("\n")}\n`;
}

/** True when two generated files hold the same features, whichever release they were read from. */
export function sameFeatures(a: string, b: string): boolean {
  return a.replace(READ_FROM, "") === b.replace(READ_FROM, "");
}
